### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [nescomtm/zad_126#1]
Generalnie wyglada to dobrze :) ale mam pare uwag
- [x] [html] w headzie najpierw dolaczaj css'y, a pozniej js'y
- [x] [js] deklaracja funkcji `showCountriesList` powinna znajdowac sie poza deklaracja funkcji `searchCountries`
- [x] niestety specyfikacja html nie pozwala, aby dzieckiem taga `<ul>` byl `<div>`, moze byc to tylko `<li>` wiec poprosze zebys przerobil strukture html generowanego js'em np. na cos takiego
```
<ul id="countries">
  <li class="country">
    <ul>
      <li>Country / Kraj : Australia</li>
      <li>Capital / Stolica : Canberra</li>
    </ul>
  </li>
  <li class="country">
    <ul>
      <li>...</li>
      <li>...</li>
    </ul>
  </li>
  ...
</ul>
```
oczywiscie moze rozwiazac to inaczej, np
```
<ul id="countries">
  <li class="country">
    <div>Country / Kraj : Australia</div>
    <div>Capital / Stolica : Canberra</div>
  </li>
  <li class="country">
    <div>...</div>
    <div>...</div>
  </li>
  ...
</ul>
```
osobiscie sugerowalbym cos takiego, choc moze byc trudniejsze:
```
<ul id="countries">
  <li class="country">
    Country / Kraj : Australia
    <ul>
      <li>Capital / Stolica : Canberra</li>
    </ul>
  </li>
  <li class="country">
    ...
    <ul>
      <li>...</li>
    </ul>
  </li>
  ...
</ul>
```

**Comment by nescomtm** [comment]
zrobiłem to pierwsze bo odczytałme to z emaila , reszty nie było w emailu (Ciekawe dlaczego  ...)

**Comment by nescomtm** [comment]
nad tym trzecim rozwiązaniem pomyśle może coś zrobię ...

**Comment by zdolny** [comment]
w mailu dostales tylko pierwszy kod, bo potem edytowalem komentarz dorzucajac kolejne

uwagi:
- [x] popraw wciecia w js, zeby bylo widac, ze te funkcje sa na tym samym poziomie
- [x] ten `if...else` jest niepotrzebny, bo robisz w nim to samo tylko dla jednego kraju nie dodajesz odstepu. Zamien to na jeden kod, wyrzuc ten brzydki `<br>` i zamiast tego dodaj w stylach odstep do odpowiedniego `li`. Ten odstep moze przeciez byc nawet jesli masz tylko jeden kraj na liscie.
- [x] wyczysc w stylach bullety (kropki) dla list - bedzie to lepiej wygladac
- [x] zmiennej `ul_` nie uzywasz

jesli chodzi o flagi panstw, to mozesz skorzystac np z:
- http://www.geonames.org/flags/x/pl.gif
- http://flags.fmcdn.net/data/flags/w580/pl.png
tutaj podpowiedz jak to ogarnac:
http://stackoverflow.com/questions/14147041/load-country-flag-from-geonames-api-using-jsonp-technique

**Comment by nescomtm** [comment]
juz to zrobiłem, ale ciekawostka bo nie dla wszystkich pań maja flagi , no chyba ze Ja używam złych kodów ....

**Comment by nescomtm** [comment]
jeszcze cos tylko wymyśle z ostylowaniem aby to jakoś wyglądało ale to dopiero po 21
